import:
    object.className: ProtImportMovies
    object.id: "2"
    object.label: pwem - import movies
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    importFrom: 0
    filesPath: /ddn/gs1/project/cryoemCore/data/projects_niehs/testing/test_scipion/20230330_test_scipion/raw/
    filesPattern: '*.tif'
    copyFiles: false
    haveDataBeenPhaseFlipped: false
    acquisitionWizard: null
    voltage: 300.0
    sphericalAberration: 2.7
    amplitudeContrast: 0.1
    magnification: 105000
    samplingRateMode: 0
    samplingRate: 0.85
    scannedPixelSize: 7.0
    doseInitial: 0.0
    dosePerFrame: 1.0
    gainFile: /ddn/gs1/project/cryoemCore/data/projects_niehs/testing/test_scipion/20230330_test_scipion/raw/gain.mrc
    darkFile: null
    dataStreaming: true
    timeout: 43200
    fileTimeout: 30
    blacklistDateFrom: null
    blacklistDateTo: null
    useRegexps: true
    blacklistFile: null
    inputIndividualFrames: false
    numberOfIndividualFrames: null
    stackFrames: false
    writeMoviesInProject: false
    movieSuffix: _frames.mrcs
    deleteFrames: false
motioncor:
    object.className: ProtMotionCorr
    object.id: "66"
    object.label: motioncorr - movie alignment
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    gpuList: 0
    doSaveAveMic: true
    useAlignToSum: true
    alignFrame0: 1
    alignFrameN: 50
    binFactor: 1.0
    cropOffsetX: 0
    cropOffsetY: 0
    cropDimX: 0
    cropDimY: 0
    splitEvenOdd: false
    doSaveMovie: false
    doComputePSD: false
    doComputeMicThumbnail: false
    extraProtocolParams: ""
    doApplyDoseFilter: true
    patchX: 5
    patchY: 5
    patchOverlap: 0
    group: 1
    tol: 0.5
    doSaveUnweightedMic: false
    extraParams2: ""
    gainRot: 0
    gainFlip: 0
    defectFile: null
    defectMap: null
    EERtext: null
    eerGroup: 32
    eerSampling: 0
    doMagCor: false
    scaleMaj: 1.0
    scaleMin: 1.0
    angDist: 0.0
    hostName: localhost
    numberOfThreads: 1
    numberOfMpi: 1
    inputMovies: 2.outputMovies
micassess:
    object.className: CryoassessProtMics
    object.id: "132"
    object.label: cryoassess - assess micrographs
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    threshold: 0.1
    threshold2: 0.1
    batchSize: 32
    gpuList: 1
    hostName: localhost
    numberOfThreads: 1
    numberOfMpi: 1
    streamingWarning: null
    streamingSleepOnWait: 5
    streamingBatchSize: 5
    inputMicrographs: 66.outputMicrographsDoseWeighted
ctffind:
    object.className: CistemProtCTFFind
    object.id: "171"
    object.label: cistem - ctffind4
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    recalculate: false
    sqliteFile: null
    inputType: 1
    avgFrames: 3
    usePowerSpectra: false
    windowSize: 512
    lowRes: 30.0
    highRes: 5.0
    minDefocus: 5000.0
    maxDefocus: 50000.0
    stepDefocus: 500.0
    slowSearch: false
    fixAstig: true
    astigmatism: 100.0
    findPhaseShift: false
    minPhaseShift: 0.0
    maxPhaseShift: 180.0
    stepPhaseShift: 10.0
    hostName: localhost
    numberOfThreads: 4
    numberOfMpi: 1
    streamingWarning: null
    streamingSleepOnWait: 0
    streamingBatchSize: 1
    inputMicrographs: 66.outputMicrographsDoseWeighted
cryolo:
    object.className: SphireProtCRYOLOPicking
    object.id: "229"
    object.label: sphire - cryolo picking
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    inputModelFrom: 0
    conservPickVar: 0.1
    lowPassFilter: false
    absCutOffFreq: 0.1
    numCpus: 1
    input_size: 1024
    boxSize: 128
    max_box_per_image: 700
    useGpu: true
    gpuList: 0
    boxSizeFactor: 1.0
    hostName: localhost
    numberOfThreads: 1
    numberOfMpi: 1
    streamingWarning: null
    streamingSleepOnWait: 0
    streamingBatchSize: 10
    inputMicrographs: 132.outputMicrographs
extract:    
    object.className: XmippProtExtractParticles
    object.id: "277"
    object.label: xmipp3 - extract particles
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    downsampleType: 1
    downFactor: 4.0
    boxSize: 64
    doBorders: false
    doRemoveDust: true
    thresholdDust: 5.0
    doInvert: true
    doFlip: false
    doNormalize: true
    normType: 2
    backRadius: -1
    patchSize: -1
    hostName: localhost
    numberOfThreads: 4
    numberOfMpi: 1
    inputMicrographs: 66.outputMicrographsDoseWeighted
    ctfRelations: 171.outputCTF
    inputCoordinates: 408.consensusCoordinates
trigger:
    object.className: XmippProtTriggerData
    object.id: "325"
    object.label: xmipp3 - trigger data
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    triggerWait: false
    outputSize: 1000
    allImages: false
    splitImages: false
    triggerSignal: false
    delay: 30
    inputImages: 277.outputParticles
relionBlobPicker:   
    object.className: ProtRelionAutopickLoG
    object.id: "365"
    object.label: relion - auto-picking LoG
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    boxSize: 130
    minDiameter: 120
    maxDiameter: 140
    areParticlesWhite: false
    maxResolution: 20.0
    threshold: -0.3
    threshold2: 5.0
    extraParams: ""
    streamingWarning: null
    streamingSleepOnWait: 30
    streamingBatchSize: 1
    hostName: localhost
    numberOfMpi: 1
    inputMicrographs: 132.outputMicrographs
consensus:
    object.className: XmippProtConsensusPicking
    object.id: "408"
    object.label: xmipp3 - picking consensus
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    inputCoordinates: [
        "229.outputCoordinates",
        "365.outputCoordinates"
    ]
    consensusRadius: 25
    consensus: -1
    mode: 0
2D:
    object.className: ProtRelionClassify2D
    object.id: "442"
    object.label: relion - 2D classification
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    isClassify: true
    is2D: true
    doContinue: false
    copyAlignment: false
    alignmentAsPriors: false
    fillRandomSubset: true
    maskDiameterA: 140
    maskZero: 0
    continueIter: last
    continueMsg: True
    doCTF: true
    hasReferenceCTFCorrected: false
    haveDataBeenPhaseFlipped: null
    ignoreCTFUntilFirstPeak: true
    doCtfManualGroups: false
    defocusRange: 1000.0
    numParticles: 10.0
    numberOfClasses: 50
    regularisationParamT: 2.0
    numberOfIterations: 25
    useFastSubsets: false
    limitResolEStep: -1.0
    doImageAlignment: true
    inplaneAngularSamplingDeg: 6.0
    offsetSearchRangePix: 5.0
    offsetSearchStepPix: 1.0
    allowCoarserSampling: false
    useParallelDisk: true
    pooledParticles: 16
    allParticlesRam: false
    scratchDir: null
    combineItersDisc: false
    doGpu: true
    gpusToUse: 0
    oversampling: 1
    extraParams: 
    hostName: localhost
    numberOfThreads: 1
    numberOfMpi: 3
    inputParticles: 325.outputParticles
monitor:
    object.className: ProtMonitorSummary
    object.id: "516"
    object.label: emfacilities - monitor summary
    object.comment: ""
    _useQueue: false
    _prerequisites: ""
    _queueParams: null
    runName: null
    runMode: 1
    inputProtocols: [
        "66",
        "171",
        "132",
        "408",
        "442",
    ]
    samplingInterval: 60
    stddevValue: 0.04
    ratio1Value: 1.15
    ratio2Value: 4.5
    maxDefocus: 40000.0
    minDefocus: 1000.0
    astigmatism: 1000.0
    monitorTime: 30000.0
    cpuAlert: 101.0
    memAlert: 101.0
    swapAlert: 101.0
    doGpu: false
    gpusToUse: 0
    doNetwork: false
    netInterfaces: 1
    doDiskIO: false
    doMail: false
    emailFrom: from@from.fakeadress.com
    emailTo: to@to.fakeadress.com
    smtp: smtp.fakeadress.com
    doInflux: false
    publishCmd: